spring:
  application:
    name: KAKAO PMS
  cache:
    ehcache:
      config: classpath:ehcache.xml
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp

  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://192.168.0.5:3306/kakaopms
    username: kakaopms
    password: kakaopms01

  main:
    lazy-initialization: true
    allow-circular-references: true

logging:
  config: classpath:logback.xml

server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 1800
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    uri-encoding: UTF-8

mybatis:
  config-location: classpath:st-ones/configuration/mybatis/mybatis-config-mysql.xml
  mapper-locations: classpath*:st-ones/configuration/mybatis/mappers/com/st_ones/**/*.xml

eversrm:
  is: false

